[project]
authors = ["example <example@example.com>"]
name = "custom_pkg"
channels = ["https://fast.prefix.dev/conda-forge", "https://prefix.dev/robostack-jazzy"]
platforms = ["linux-64", "win-64"]

[tasks]
build = "colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release"

[target.linux-64.tasks]
vscode = 'env -u LD_LIBRARY_PATH code .'

[tasks.start]
cmd = "ros2 run custom_pkg custom_node"
depends-on=["build"]

[dependencies]
compilers = ">=1.9.0,<2"
pkg-config = ">=0.29.2,<0.30"
ninja = ">=1.12.1,<2"
ros-jazzy-desktop = "*"
colcon-common-extensions = "*"
rosdep = "*"
conda-build = ">=25.1.2,<26"
conda-verify = ">=3.4.2,<4"
rattler-build = "*"


[target.linux-64.dependencies]
python-devtools = "*"         # Optional but useful
python = "*"            # This is critical for CMake to find Python
pybind11 = "*"                # Optional, if you work with bindings
numpy = "*"
lttng-ust = "*"
