name: Build Debian Packages (ROS2 Jazzy)
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build-debian-packages:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install libsdl2-dev -y
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4
      - name: Build Debian packages
        uses: ichiro-its/ros2-build-debian-action@main
        with:
          ros2-distro: jazzy
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            REPO_FULL=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
            TAG_NAME=$(gh release view --repo "$REPO_FULL" --json tagName --jq ".tagName")
  
            gh release upload "$TAG_NAME" package/*.deb --repo "$REPO_FULL"